import type { Metadata } from "next";
import { Figtree, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Background from "@/components/background";
import CursorDecorator from "@/components/cursor-decorator";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <html lang="en" className={cn("font-sans", figtree.variable)}>
      <body className={`${geistMono.variable} antialiased relative min-h-screen`}>
        <Background />
        <CursorDecorator color="#7FC8FF">{children}</CursorDecorator>
      </body>
    </html>
  );
}
