import type { Metadata } from "next";
import { Figtree, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Background from "@/components/background";
import CursorDecorator from "@/components/cursor-decorator";
import ThemeToggle from "@/components/theme-toggle";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const themeInitScript = `
  (() => {
    const storageKey = "theme";
    const storedTheme = window.localStorage.getItem(storageKey);
    const theme =
      storedTheme === "light" || storedTheme === "dark"
        ? storedTheme
        : window.matchMedia("(prefers-color-scheme: dark)").matches
          ? "dark"
          : "light";
    document.documentElement.dataset.theme = theme;
    document.documentElement.classList.toggle("dark", theme === "dark");
  })();
`;

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <html suppressHydrationWarning className={cn("font-sans", figtree.variable)} lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className={`${geistMono.variable} antialiased relative min-h-screen`}>
        <Background />
        <ThemeToggle />
        <CursorDecorator color="#7FC8FF">{children}</CursorDecorator>
      </body>
    </html>
  );
}
